name: Build docker

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push - dump1090
        uses: docker/build-push-action@v5
        with:
          push: true
          context: ./dump1090
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/dump1090:latest
          platforms: linux/amd64,linux/arm64

      - name: Build and push - fr24feed
        uses: docker/build-push-action@v5
        with:
          push: true
          context: ./fr24feed
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/fr24feed:latest
          platforms: linux/amd64,linux/arm64